### PR TITLE
Add support for getting clients in a given room (Works across multiple nodes)

### PR DESCRIPTION
**Pull request by FREEZX**
I added basic support for the redis adapter for storing and getting clients (As an async call) or a room in the redis database.
I didn't manage to do the exit cleanup correctly, so after normal exit, rooms are still filled up with the same (now unexisting) socket ids. Quitting with Ctrl+C or the kill signal should work as expected.

Also added a test for the clients function call

### CODE REVIEW

**Comment by cha0s** [comment]
I've been looking into this and due to the issues with synchronization it seems like it would be better to use the pubsub functionality to query the adapter for the clients in a room instead of trying to replicate the client list across the adapters.

So, instead of duplicating a full room list on each worker, instead each worker would query the other workers in real time when they needed a list of the clients in a particular room, using http://redis.io/commands/pubsub commands.

I am going to explore this method.

**Comment by rauchg** [comment]
We're definitely not going to do replication.

**Comment by cha0s** [comment]
I did some exploration on this task and I can't get it working. Unfortunately redis pubsub doesn't allow us to use introspection for pattern subscriptions (so we can't know when all workers have responded with their client list), and even if it did, we'd run into the case of possible race conditions of a worker going down between the pub of the 'clientrequest' message, and the reception of the 'clientresponse' message.

If anyone has an idea how we could accomplish this without introspection or replication I'm open to ideas and would be willing to write some code. I am starting to wonder if it is possible to do this without replication at least for redis, and even using something like ZeroMQ seems to require having a central broker with 'eventually consistent' state management.

**Comment by rauchg** [comment]
@cha0s I think pub/sub could be _good enough for most cases considering the unsuitability of redis for this task_.

The requestor would emit the client aggregation request with a random uid (which solves the introspection problem), and then have a maximum timeout of how long it's willing to wait for responses from other nodes (like `100` ms).

**Comment by cha0s** [comment]
Well we still can't solve introspection that way, because all workers 
would have to know the uid in advance to be able to request the # of 
channels listening to it. However we *would* need to generate a uid to 
ensure that each request has a unique fingerprint (so responses don't 
get mixed up), and the response would need to return it.

We could easily do the timeout pattern. The problem is that since we 
don't have reliable introspection, the call will *always* take 100ms 
because there is no reliable way to know all clients who are subscribed 
to receive the message. But then...

An alternative would be to hardcode the clientrequest subscription key 
(like "socket.io#clientrequest", it could be overridden in options too), 
however then we would have to encode the 'real' client uid in the 
package to do the 'same uid' check (in addition to another request uid). 
This gives us the ability to finally use introspection though since all 
workers will know the key in advance (barring separate workers sending 
in that key differently through config options, but that's an 
application bug).

**Comment by rauchg** [comment]
My thinking is that requesting the clients list is something you should rarely (if ever) do. That's why the max timeout downside might not be bad.

**Comment by rauchg** [comment]
(it's still a non-solution)

**Comment by rauchg** [comment]
The other more-complex lower-latency more-reliable alternative being implementing discovery and heartbeats for a mongodb-style replica set node registry, but without the replication.

**Comment by rauchg** [comment]
With redis itself acting as the registry-keeper.

**Comment by cha0s** [comment]
Linking the PR I made: https://github.com/Automattic/socket.io-redis/pull/50

I reduced the timeout to 10ms (seems reasonable, redis is pretty darn fast)

**Comment by peteruithoven** [comment]
I don't understand why @cha0s idea couldn't work. 
- You publish a getClients request, with a newly created uid
- Other instances receive this request, with the uid
- They publish their client info, with the uid
- The initiator / requester collects all the incoming info with the uid he send, until the fixed timeout is passed. 

Why would that not work?

**Comment by FREEZX** [comment]
@peteruithoven 
That should work but relying solely on timeout means a possibility for incorrect data.

**Comment by cha0s** [comment]
The PR I linked (in addition to the other two linked from that page) indeed demonstrate that it does work :)

The best case actually requires no timeout, when the client request is sent, we look up the number of subscribers to the channel (the # of nodes we're requsting from) and then receive the same number of replies back, concatenating them. The only time this fails is if a node goes down during the client request. It's still possible that this could happen, and is the sole purpose of the timeout.

It's a pretty small window for inconsistency but I will acknowledge that the window is there, yes

**Comment by FREEZX** [comment]
@cha0s Your solution looks good to me.

**Comment by peteruithoven** [comment]
Nice! 
I didn't know you could get the number of subscribers, that solves a lot.

**Comment by rauchg** [comment]
@cha0s I really love your introduction of a best case scenario.

**Comment by peteruithoven** [comment]
What's the status of this pull request?

**Comment by allthetime** [comment]
I'm also curious about this... would be a great feature to have!

**Comment by rauchg** [comment]
This is the next immediate thing I'm including. It's almost there.

—
@rauchg <https://twitter.com/rauchg>

**Comment by janckerchen** [comment]
+1

**Comment by xfg** [comment]
We wait.

**Comment by andreabadesso** [comment]
+1

**Comment by hems** [comment]
I didn't manage to check the source code for this pull request, but i'm wondering if a 'pure redis' implementation wouldn't be the case?

As in: each worker saving it's own state on redis?

````
user enters 
 ~> add user.id to room:id SET
 ~> add room.id user:in_rooms SET

user leaves
 for each id in user:in_rooms SET
   <~ remove user.id to room:id SET

server shutdown
  for each socket.id in server.socket.clients
    for each id in user:in_rooms SET
      <~ remove user.id to room:id SET
````

The only issue i can see is if the worker doesn't shutdown gracefully, other than that this implementation should solve the issue?

**Comment by artofspeed** [comment]
@FREEZX I have visited your patched version of this repo (https://github.com/FREEZX/socket.io-redis) I was wondering how to use your .clients() function to get all clients in a room.

Currently I'm using this:
```javascript
var adapter = require('socket.io-redis')({ host: 'localhost', port: 6379 })
io.adapter(adapter);

// Get all clients in a room
adapter.prototype.clients(room, function(err, data){
    console.log(data); // ['K0ce8P0WP_4vM2evAAAB', ...]
});
```

Is this a good way to do it?

**Comment by FREEZX** [comment]
@artofspeed Are you using my fork of socket.io?
You should be able to do io.clients() with my fork.

**Comment by hems** [comment]
@FREEZX with your fork can we know when a user entered or left a room?

i had to implement this on my application and end up having to do a couple of workarounds with sockets.id which i don't even know if it's unique across multiple instances running.

**Comment by ebourmalo** [comment]
@rauchg @FREEZX Any news about the merge of this PR please :)?

**Comment by FREEZX** [comment]
I do not need this anymore, i've switched to primus with the ws transformer, so i won't be working on this year old PR. If anyone wants to take over, be my guest.

**Comment by perrin4869** [comment]
@FREEZX can primus-cluster and primus-rooms find out the number of clients inside a room outside the box?

**Comment by ebourmalo** [comment]
@FREEZX interesting. what plugin do you use to replace this redis adapter and broadcasts messages to running node instances with primus ?

**Comment by jsdream** [comment]
I'm also interested in this :)

**Comment by FREEZX** [comment]
@perrin4869 Only if you use https://github.com/cayasso/primus-rooms#primusroomroomclientsfn and then count the number of results. It should be fairly straightforward to add a count feature.
@ebourmalo You can use https://github.com/cayasso/primus-rooms with https://github.com/mmalecki/primus-redis-rooms

**Comment by luislobo** [comment]
+1, any news on this?

**Comment by jsdream** [comment]
Any chance this going to be merged at all? Lots of people interested in the feature. 
Is this not being merged because of clean up limitation on exit or there is something else?

**Comment by jsdream** [comment]
Hello @FREEZX! 

Looks like I also decided to go with Primus, but not sure which transformer is better to use. Is `ws` a viable enough solution?

**Comment by jsdream** [comment]
Just found a nice article on topic of choosing transformers (with performance tests): https://medium.com/@denizozger/finding-the-right-node-js-websocket-implementation-b63bfca0539

**Comment by FREEZX** [comment]
@jsdream I made a detailed benchmark including all node websocket technologies i found while developing my own web framework in order to choose the best possible approach:
http://nukejs.com/#/benchmarks
https://www.dropbox.com/s/6dgnftmjcjf2g5o/bare_conf.pdf

**Comment by jsdream** [comment]
@FREEZX Thank you very much for the response. Btw, your framework looks very interesting. Will consider it for future projects ;-)

**Comment by FREEZX** [comment]
@jsdream Thanks, hope you enjoy using it. :) I was previously working with mean.js, but it had some bugs, and it was difficult making it suit my needs, work with websockets and making it scalable, so instead i went out and did this.

**Comment by jsdream** [comment]
@FREEZX Yeah, currently I struggling with MEAN.js to get websockets working in cluster mode. On the benchmark you've provided I noticed this: "Nuke.js uses the websockets transformer by default, because it is the fastest transformer available, and **does not require sticky sessions support on your load balancer.**" 

Does this really mean there is no handshake problem when using **ws** module with **primus** and **node.js cluster**? Sorry for such kind of questions, I am just really new to websockets.

**Comment by FREEZX** [comment]
@jsdream Yes, since it doesn't require sticky sessions, and judging from the manual, that's the only issue that breaks primus with cluster. I also remember asking the same question on the primus IRC, i think i got the same response. 
If you have other questions, join them on IRC:

server: irc.freenode.net
room: #primus

**Comment by jsdream** [comment]
Cool. Thank you again!

**Comment by stephengardner** [comment]
There's been a lot of discussion going on here.  Inability to support this is kind of making me look towards other libraries...

**Comment by Jokero** [comment]
@rauchg Two years... Will it be merged?

**Comment by austinkelleher** [comment]
+1 What's the status on this? @rauchg

**Comment by JCMais** [comment]
This PR is outdated, and probably broken since new updates to both socket.io and the adapter. As the PR author has abandoned it (which I cannot condemn), it's probably not going to get merged any time soon, if ever.

**Comment by felixSchl** [comment]
I have had an idea: how about for the lifetime of the connected socket we periodically set a key on redis with a TTL of some time. If the socket disconnects, or if the server crashes, redis would remove the keys using it's `EXPIRE` mechanism.

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io-redis/pull/109

**Pull request closed without merging**
