### PR TITLE
Replacing msgpack-lite by msgpack due to data lost

### PR DESCRIPTION
**Pull request by jeroenrinzema**
See issue #172

### CODE REVIEW

**Comment by darrachequesne** [comment]
Were you able to reproduce the issue?

**Comment by jeroenrinzema** [comment]
I was unfortunately not able to reproduce the bug in socket.io-redis but i was able to reproduce a part of the [bug](https://runkit.com/5887a3a8fde3f600145f514a/588b0317d5054b00140e4aba) in msgpack-lite and msgpack-js. It looks like something goes wrong with the algorithm inside of the dependencies when encoding the message. I think that it is then anyhow a good idea to switch to a different dependency. msgpack passed the tests and didn't show the same strange behavior.

**Comment by darrachequesne** [comment]
Without a proper way to reproduce, I'm afraid that we can't make sure it's really related to `msgpack-lite`...

Besides, it seems that `msgpack` does not compile under Windows: https://github.com/pgriess/node-msgpack/issues/70

Regarding your example, may I ask what it is supposed to show?

screenshot from 2017-01-31 09 58 38

**Comment by jeroenrinzema** [comment]
I see that something went wrong this is the right [example](https://runkit.com/5887a3a8fde3f600145f514a/588b0317d5054b00140e4aba) I will keep on trying  to reproduce the bug.

**Comment by darrachequesne** [comment]
Thanks for the example.

It might be linked to https://github.com/socketio/socket.io-redis/pull/157. Are you still using the `return_buffers` option? Or a custom `subEvent`?

**Comment by valeriansaliou** [comment]
Why don't we consider just dropping MessagePack? We've been running SocketIO-Redis @crisp-im over 1+ year, and as we are gaining more and more pressure on our SocketIO workers over time we've started reviewing what we could optimize.

It turned out that SocketIO-Redis use of MessagePack was causing ~20% of our SocketIO workers CPU load (notice: we do stream some large JSON payloads sometimes). Forking SocketIO-Redis and moving it to the Node native JSON.parse() / JSON.stringify() implementation fixed the issue.

Plus, looking at the Redis MONITOR command; it appears that MessagePack does not reduce the size of messages that much, as MessagePack-optimized binary blobs get string-encoded when wired in/out of Redis (Redis only accepts string contents). Thus, a lot of MessagePack compact-binary blobs get encoded/escaped as multiple-chars strings; which increase the overall size of the MessagePack payload that is streamed across SocketIO workers.

**Overall, after switching from MessagePack to bare-bone JSON we've seen an overall CPU usage decrease of ~20%, and a Redis Pub/Sub I/O increase of ~10-20%. Which is why we'll stick to our JSON fork over the long run.**

--

Anyway, if you want to stick to a MessagePack implementation, I'd recommend [Notepack](https://www.npmjs.com/package/notepack). We've been previously using it on other high-load services (to pass data between our internal Node workers using RabbitMQ) w/o that much impact on CPU (however we've also replaced it w/ JSON). If you perform some benchmark between Node MessagePack implementations, you'll notice Notepack is the fastest. We did not encounter any issue using it (encoding special extended UTF-8 chars; encoding/decoding large JSON, etc).

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io-redis/pull/218.

**Pull request closed without merging**
