### PR TITLE
latest dependencies

### PR DESCRIPTION
**Pull request by knoxcard2**
latest dependencies

### CODE REVIEW

**Comment by knoxcard2** [comment]
Only failing on Node 6 and lower:
https://travis-ci.org/socketio/socket.io-redis/builds/594885163?utm_source=github_status&utm_medium=notification

**Comment by knoxcard2** [comment]
@darrachequesne

**Comment by ThreeDfish** [comment]
If that is the case you should remove node 6 from travis.yml and add node 10 and node 12.

Also, it is a bad idea to specify "latest" for the version in production code for wide use, because you never know when a breaking change may be made in a new version of a dependency.

**Comment by darrachequesne** [comment]
Please do not use `latest` in production. Stay safe!

**Pull request closed without merging**
