### PR TITLE
Add a local flag that can prevent the adapter from publishing the emi…

### PR DESCRIPTION
**Pull request by tal-beja**
…t to the server

### CODE REVIEW

**Comment by tal-beja** [comment]
Works with this pull request:
https://github.com/socketio/socket.io/pull/2628

**Comment by darrachequesne** [comment]
@tal-beja hi! May I ask what your use case is please?

**Comment by tal-beja** [comment]
When several insrances of a server recieve the same even from a third party (not from a client), each server instance broadcast the event to all his clients. 
If I use the redis adapter each server publish to redis about the event and thus each client recieve the same event times the number of the server instances. 
With the local flag, and the change in the redis adapter, each server instance send the event only to his client, so each client recieve only one uniqe event.

**Comment by darrachequesne** [comment]
@tal-beja sorry for the delay. Could you please rebase and add some tests please?

Also, is the `redis` version bump mandatory for this to work? Do you know what the impact is? (the changelog seems huge, especially towards the pub/sub mechanism)

**Comment by KristjanTammekivi** [comment]
_bump_

**Comment by 17289kjhajshd389210h** [comment]
+1 @tal-beja

**Comment by darrachequesne** [comment]
Merged as https://github.com/socketio/socket.io-redis/commit/c38e32304d0837834a10cf30e86c3557f111424f. Thanks!

**Pull request closed without merging**
