### PR TITLE
Suggestion for implementation of clients API

### PR DESCRIPTION
**Pull request by cha0s**

### CODE REVIEW

**Comment by cha0s** [comment]
I bumped socket.io and socket.io-client in the dev dependencies, obviously they will have to be bumped again if this goes in to reflect the other PRs I've made on this topic.

**Comment by cha0s** [comment]
https://github.com/Automattic/socket.io-adapter/pull/24
https://github.com/Automattic/socket.io/pull/1966

Just to link them together

**Comment by rauchg** [comment]
So, this is a great foundation for this patch. Thanks a lot for submitting this PR. 

I think it's going to require some minor refactoring to adapt to our goal of [getting rid of pattern subscriptions](https://github.com/Automattic/socket.io-redis/pull/46). Otherwise, with minor potential API changes, this is the solution we'll deploy.

The API changes I'm still debating in my mind are: 
- do we care about an API to only receive _local_ clients (to the specific node), or do we make it transparent and always expose all nodes?
- do we care about filtering by room?

**Comment by rauchg** [comment]
So far I think I'm No - Yes on those questions.

**Comment by rauchg** [comment]
If the answers were Yes - Yes, I think we should consider exposing two methods `clients` and `allClients`

**Comment by cha0s** [comment]
Interesting, first I saw #46. It's a really good idea to do things that way.

I think it makes sense to filter based on namespace/room. Especially once #46 goes in it'll be even less overhead since we won't have to hit every namespace in every node

**Comment by cha0s** [comment]
Oh, also I'm not sure about the local/remote clients thing. I'm leaning towards No - Yes myself, because I don't think the overhead will be too high, and once you get those IDs you could check them against the local state (though, peeking into internals, which isn't polite...)

Honestly when I started this out I was envisioning being able to use a socket ID from a remote node to be able to emit a message from another node, but that seems like a convulted process as well. I almost wonder if this API should be introduced only if there is some kind of '(emit|broadcast)To' function that instead of operating on a socket, takes a socket ID. I have been struggling with the idea that perhaps the use case for clients as it stands isn't as useful as I thought. However, if enough people want it I don't mind anyway.

**Comment by rauchg** [comment]
@cha0s the API you mention already exists. Every socket joins a room identified by their session id.
http://socket.io/docs/rooms-and-namespaces/#default-room

**Comment by cha0s** [comment]
I totally forgot about that. Obviously that makes this a lot more useful than I thought when I wrote that post!

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io-redis/pull/109

**Pull request closed without merging**
